[project]
name = "mortal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "tensorboard>=2.20.0",
    "toml>=0.10.2",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
]
